### ISSUE TITLE
Missing description text at result page

### ISSUE THREAD

**Issue by ovesemart** [swedenconnect/test-my-eid#34]
A minor issue at the result page. The description text for attribute ID seems to be missing. See picture below

<img width="682" alt="Skärmavbild 2020-10-07 kl  15 29 49" src="https://user-images.githubusercontent.com/36661180/95337555-3e752e80-08b2-11eb-9d99-fb40d530ab84.png">

**Comment by martin-lindstrom** [comment]
Fixed in 1.3.1.
