### ISSUE TITLE
java.lang.ClassCastException when running the application

### ISSUE THREAD

**Issue by vptu** [swedenconnect/test-my-eid#38]
Dear authors of this application,

i tried to run your application, but unfortunately i run into an issue, which i can't fix.

Error creating bean with name 'openSAML' defined in se.swedenconnect.eid.sp.TestMyEidApplication: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [se.swedenconnect.opensaml.OpenSAMLInitializer]: Factory method 'openSAML' threw exception; nested exception is java.lang.ClassCastException: class org.opensaml.xmlsec.encryption.impl.ConcatKDFParamsImpl cannot be cast to class se.swedenconnect.opensaml.xmlsec.encryption.ConcatKDFParams (org.opensaml.xmlsec.encryption.impl.ConcatKDFParamsImpl and se.swedenconnect.opensaml.xmlsec.encryption.ConcatKDFParams are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader

I tried to this application on a Cloud Foundry stack and on a Docker stack, both with the same issue.

Build with maven 3.8.1 and JDK11 with target JRE11

Steps to reproduce:
- Assign Spring profile "sandbox"
- Build with mvn clean install
- Created Docker image with docker build -t 
- Run the image with docker run and the 3 ports exposed.

Any idea how to fix this?

Many thanks and best regards!

**Comment by martin-lindstrom** [comment]
After restructure this should not be happening anymore
