### ISSUE TITLE
Icon fails to load

### ISSUE THREAD

**Issue by ovesemart** [swedenconnect/test-my-eid#73]
There is an icon that fails to load, test my Eid keeps repeating the load (redirecting) until it fails.

<img width="1202" alt="Skärmavbild 2024-04-17 kl  08 08 15" src="https://github.com/swedenconnect/test-my-eid/assets/36661180/34b4c108-fe3d-4c91-a68a-dd532c285c32">

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/test-my-eid/pull/87
